### ISSUE TITLE
Permission to use source code?

### ISSUE THREAD

**Issue by shadytony222** [np98765/BattleKits#112]
Hello. I know in your license it says no configuring, but could i get rights to use and configure the plugin, whether its pay a certain amount or give you create in my server. Thankyou

**Comment by np98765** [comment]
We're licensed under GPLv3 (http://dev.bukkit.org/licenses/7-gnu-general-public-license-version-3-gplv3/), so you can edit the source pretty freely. We appreciate pull requests, if you want to contribute back :)

You are definitely allowed to configure the plugin (that's why there's a configuration file in place).
