### ISSUE TITLE
Wont Generate BattleKits Folder

### ISSUE THREAD

**Issue by Lusydia** [np98765/BattleKits#128]
Is it just me or is anyone else having there battlekits not generate a folder

l am Lusydia from TheFourGamerteers and I am in the middle of making a server and i need battlekits

what craftbukkit do i need?

**Comment by lol768** [comment]
There's two problems with this issue! Congratulations!

# You didn't follow the issue requirements here: #1

# You didn't give me any error information

So, I'm gonna take a huge guess here and assume you get an InvalidMajorMinorVersion error on startup. This means you need to update to Java 7.

I'm closing this issue now since it's invalid. I'll reopen it if you follow #1
