### ISSUE TITLE
BattleKits Error: "Please choose a valid Kit" - Kit Not Found

### ISSUE THREAD

**Issue by Zzbiohazardx** [np98765/BattleKits#150]
-Closed

**Comment by Zzbiohazardx** [comment]
Can any one help me?

**Comment by Zzbiohazardx** [comment]
I really need help with this. This will help me fix my Server and help it get released!

**Comment by lol768** [comment]
Sorry, I don't support PEX due to it's breaking nature.

**Comment by Zzbiohazardx** [comment]
You don't realize how much you could be of help to me. You choose to be lazy, it doesn't matter if you don't support PEX. I could AT LEAST get some kind of help from you, beings you ARE the Dev of the Plugin. You have a support forums for a reason. It works with PEX but there is something wrong with it.

**Comment by lol768** [comment]
Oh wow. So now we jump to the accusations of being lazy and your conclusion that it can't possibly be your or PEX's fault and it's obviously my fault. I have **absolutely no obligation whatsoever** to provide support of any kind and I have no wish to provide it to anyone that behaves in such an arrogant, selfish manner. I do not support PEX due to its many issues (https://docs.google.com/document/d/1BIgAU7senSG1hY0BjQAQFAnbuOqFhpln7ffN6pkOp4s/edit)..

I don't give a damn if this causes you inconvenience and delays your server - go and find another kit plugin and demand support from that developer instead.

Have a nice day

**Comment by Zzbiohazardx** [comment]
Sorry, I was just a bit up set and was causing problems. I didn't mean it. I'll try using a different form of permissions. Thanks.
