### ISSUE TITLE
Config keeps resetting to default

### ISSUE THREAD

**Issue by rumbleiv** [np98765/BattleKits#2]
CraftBukkit version: Bukkit 1.4.2 R0.2
Plugin list: World portal, XpStrength, nodrop, battlekits, worldedit, nocheatplus, pail, fastsoup, buycraft, vault, autotimeday, permissionex, modifyworld, worldguard, treeassist, piratestick, Pailplus, essentials, chatmanager, esseentialsspawn, essentials chat, autorank
BattleKits version:  BattleKits 1.3 for CB 1.4.2-R0.2 19 hours ago
Config file link (pastebin.com): It keeps resetting to the default..
When does the error occur?
Everytime I restart server for a reload.
Steps to reproduce error:
Restart server.

**Comment by lol768** [comment]
Every time the server reloads/restarts, the config is saved. This overwrites any changes you have made and is intentional to ensure that kit tracking/lives are not lost on restart. It's very easy to fix, so next time you want to modify the config follow these steps:
- Edit the file and make any changes
- Run /pvp reload in-game or from the console
- At this point the new config is in memory and the default should not overwrite your changes

If you ever make changes, simply remember to use /pvp reload to tell BattleKits to take your changes into account. It also has the advantage of not requiring any other plugins to restart.
