### ISSUE TITLE
An internal error has occurred while attempting to perform this command.

### ISSUE THREAD

**Issue by ozmiumGIT** [np98765/BattleKits#203]
I'm having issues with the plugin since I added a "materializer" kit, so I am guessing it is only the kit.yml. Nonetheless, I added #1.

CB Version: CraftBukkit version git-Spigot-52c130f-8
1ab957 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Plugin List: Plugins (22): WorldEdit, EmptyWorldGenerator, CompassChase, Essentials, EssentialsChat, PermissionsEx, CrackShot, Buycraft, Modifyworld, HeadshotEffects, Vault, TrailGUI, EssentialsSpawn, Multiverse-Core, ProtocolLib, WorldGuard, BattleKits, TitleManager, VanishNoPacket, Autorank, Multiverse-Portals, MagicSpells

BK Version: v. 2.1.1

kits.yml: http://pastebin.com/nPRSvQry
server log: http://pastebin.com/XMW9Q4J5

Steps to reproduce/When does it occur: The error can be simply reproduced by typing in /kits, and it will give me the following message "An internal error has occurred while attempting to perform this command." When typing kit in console it gives me the following: http://pastebin.com/2VfFhEsR

Other relevant info: I use the magicspells plugin, which may be of some useful info, but I think is irrelevant because it worked with kit "blotter" Currently I don't have a permissions setup (I plan to set it up later), but that may too be of irrelevant info.
Online yaml parser gives me the following:
ERROR:

while parsing a block mapping
  in "<unicode string>", line 3, column 1:
    kits:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 309, column 2:
     materializer:
     ^
But it won't let me share the link. Sorry for the inconvenience.

If I missed anything please tell me, I'd like to get this solved and get it over with.

Thanks!

**Comment by lol768** [comment]
Hi there,

This plugin isn't maintained anymore but I'm happy to give you some pointers on the issues with your configuration file.

Firstly, thanks for providing all the information. As you expected, this is indeed a configuration file issue (and quite a simple one actually - I imagine you'll see the problem immediately once you know which lines it's on).

https://gist.github.com/lol768/85caafd4e2d6acff5534#file-gistfile1-yml-L16

Since the ':' character means something in a YAML file, it has to be escaped or wrapped in quotes. The easiest way of addressing this is to change the lines I've marked in your config file with a comment (see above gist) to include single quotes:

Before:
`'0': 267 16:1`

After:
`'0': '267 16:1'`

Hope this solves the problem for you and happy holidays :)
