### ISSUE TITLE
How Do I Spawn In Potions?

### ISSUE THREAD

**Issue by goomonster3** [np98765/BattleKits#71]
Hey, How do I spawn in potions with battlekits?

I am using CB Version R3 1.4.6

I am using BattleKits Version 1.9.5

All i need is a speed II potion and Strengh potion.. Not Splash. Im just not sure....

Please help ^^Tell me if that isn't detailed enough... 

Thanks,
Goo

**Comment by goomonster3** [comment]
Oh ! My config is like this:

# Kit definitions

# This is where you can add your own kits and customise various details

kits:
  Archer:
    active-in: all
    on-give-message: '&cGo and shoot some targets!'
    cost: 
    xpLevels: 
    tagPrefix: '&a'
    commands:
    - tell <player> Enjoy your kit :)
    items:
      helmet: leather
      chestplate: leather
      leggings: leather
      boots: leather
      helmetDurability: 
      helmetColor: '#FF0000'
      chestplateColor: '#FFFF00'
      leggingColor: '#FF00FF'
      bootColor: '#0000FF'
      bootsEnchant: 2:1 3:5
      '0': 261 49:2
      '1': '282'
      '2': '282'
      '3': '282'
      '4': '282'
      '5': '282'
      '6': '282'
      '7': '282'
      '8': '282'
      '9': '282'
      '10': '282'
      '11': '282'
      '12': '282'
      '13': '282'
      '14': '282'
      '15': '282'
      '16': '282'
      '17': '282'
      '18': '282'
      '19': '282'
      '20': '282'
      '21': '282'
      '22': '282'
      '23': '282'
      '24': '282'
      '25': '282'
      '26': '282'
      '27': '282'
      '28': '282'
      '29': '282'
      '30': '282'
      '31': '282'
      '32': '282'
      '33': '282'
      '34': '262:64'
      '35': '262:64'
      names:
        '0': '&cSUPER KNOCKBACK BOW'
  Standard:
    active-in: all
    items:
      helmet: iron
      chestplate: iron
      leggings: iron
      boots: iron
      '0': 267 16:1
      '1': '282'
      '2': '282'
      '3': '282'
      '4': '282'
      '5': '282'
      '6': '282'
      '7': '282'
      '8': '282'
      '9': '282'
      '10': '282'
      '11': '282'
      '12': '282'
      '13': '282'
      '14': '282'
      '15': '282'
      '16': '282'
      '17': '282'
      '18': '282'
      '19': '282'
      '20': '282'
      '21': '282'
      '22': '282'
      '23': '282'
      '24': '282'
      '25': '282'
      '26': '282'
      '27': '282'
      '28': '282'
      '29': '282'
      '30': '282'
      '31': '282'
      '32': '282'
      '33': '282'
      '34': '282'
      '35': '282'
  Jumper:
    active-in: all
    items:
      helmet: iron
      chestplate: gold
      leggings: iron
      boots: iron
      '0': 272 16:1
      '1': '368:5'
      '2': '282'
      '3': '282'
      '4': '282'
      '5': '282'
      '6': '282'
      '7': '282'
      '8': '282'
      '9': '282'
      '10': '282'
      '11': '282'
      '12': '282'
      '13': '282'
      '14': '282'
      '15': '282'
      '16': '282'
      '17': '282'
      '18': '282'
      '19': '282'
      '20': '282'
      '21': '282'
      '22': '282'
      '23': '282'
      '24': '282'
      '25': '282'
      '26': '282'
      '27': '282'
      '28': '282'
      '29': '282'
      '30': '282'
      '31': '282'
      '32': '282'
      '33': '282'
      '34': '282'
      '35': '282'
      names:
        '1': '&2Jumpers Pearls'

Thanks again,
Goo

**Comment by lol768** [comment]
Hi Goo!

This can be quite confusing, so I'm going to write a little step-by-step guide. I'll probably cross-post this to the FAQ, too.
1. Goto [this page](http://www.minecraftwiki.net/wiki/Potions) on the wiki and find the data value of the potion item you wish to add to a kit. In our case, we want a speed II and strength drinking potion. The damage value for the speed II potion is `8226` and the 3-minute strength potion's data value is `8201`. We know the item id for a potion is 373, and the data value tells Minecraft the potion type. Splash potions have the same id (373) but different data values. These are listed on the wiki too.
2. Now we know the id and data value, we can add it to the kit file. All item entries are done in the following format:

``` yaml
'slot-id': 'itemID:amount:durability enchantmentID:level'
```

Since we don't need an enchantment, we can simply use this:

``` yaml
'slot-id': '373:1:<damageValue>'
```

Ensure you insert the damage value from step 1.

Hope this is of some help.
